### ISSUE TITLE
Build failed error

### ISSUE THREAD

**Issue by muralidharansa** [rajasegar/ember-responsive-tabs#2]
Hi,
  If I installed the ember-responsive-tabs my application build was failed and display the following error message

`The Broccoli Plugin: [SimpleConcat: Concat: Vendor Styles/assets/vendor.css] failed with:
Error: ENOENT: no such file or directory, stat 'D:\sample\tmp\simple_concat-input_base_path-Quze8g7v.tmp\0\app\styles\app.css'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at FSMonitor._measure (D:\sample\node_modules\ember-cli\node_modules\heimdalljs-fs-monitor\index.js:66:21)
    at Object.statSync (D:\sample\node_modules\ember-cli\node_modules\heimdalljs-fs-monitor\index.js:82:30)
    at Concat.keyForFile (D:\sample\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\index.js:87:20)
    at Array.map (native)
    at Concat.CachingWriter._conditionalBuild (D:\sample\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\index.js:109:65)
    at D:\sample\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\read_compat.js:61:34
    at tryCatch (D:\sample\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (D:\sample\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:554:13)

The broccoli plugin was instantiated at:
    at Concat.Plugin (D:\sample\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at Concat.CachingWriter [as constructor] (D:\sample\node_modules\ember-cli\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\index.js:18:10)
    at new Concat (D:\sample\node_modules\ember-cli\node_modules\broccoli-concat\concat.js:32:17)
    at module.exports (D:\sample\node_modules\ember-cli\node_modules\broccoli-concat\index.js:26:10)
    at EmberApp.concatFiles (D:\sample\node_modules\ember-cli\lib\broccoli\ember-app.js:370:10)
    at EmberApp._concatFiles (D:\sample\node_modules\ember-cli\lib\broccoli\ember-app.js:383:15)
    at EmberApp.styles (D:\sample\node_modules\ember-cli\lib\broccoli\ember-app.js:1333:28)
    at EmberApp.toArray (D:\sample\node_modules\ember-cli\lib\broccoli\ember-app.js:1641:10)
    at EmberApp.toTree (D:\sample\node_modules\ember-cli\lib\broccoli\ember-app.js:1662:30)
    at module.exports (D:\sample\ember-cli-build.js:33:14)`

**Comment by rajasegar** [comment]
As far as i can see its working for me, just tried out in a sample repository, the problem i see here is the broccoli tool is not able to find some app.css from vendor.
Can you remove your tmp/ and dist/ folder completely and try again. It will trigger a full build and clean up your build directories.
